"""
Django settings for avocat_yassine project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# True en prod/serveur web ; False pendant migrate/makemigrations/test/collectstatic
AUDIT_ENABLED = not any(cmd in sys.argv for cmd in ("migrate", "makemigrations", "test", "collectstatic"))


# === ملفات ثابتة (CSS / JS / صور) ===
STATIC_URL = '/static/'

# في وضع التطوير:
STATICFILES_DIRS = [
    BASE_DIR / 'static',   # مجلدك المحلي الذي يحتوي ملفاتك
]

# في الإنتاج: سيتم نسخ كل شيء هنا بعد collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'

# === ملفات الميديا (صور مرفوعة) ===
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y*vg0lu+2jz9q8l-yb0!l6$*!!^36fu%p9c$gj8d13&i69%plc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'avocat_app.apps.AvocatAppConfig',
    'django_extensions',
]

# === Audit switches & defaults ===
AUDIT_ENABLED = True
AUDIT_REDACT_FIELDS = ["password", "mot_de_passe", "secret", "token", "authorization"]
AUDIT_RETENTION_DAYS = 365  # احتفاظ سنة
TOKEN_IDLE_TIMEOUT_SECONDS = 5 * 60
TOKEN_MIN_TOUCH_INTERVAL_SECONDS = 60  # لتقليل الكتابة
AUTH_TOKEN_COOKIE_SECURE = True
AUTH_TOKEN_COOKIE_HTTPONLY = True
AUTH_TOKEN_COOKIE_SAMESITE = "Lax"
LOGIN_URL = "/auth/login/"
LOGIN_REDIRECT_URL = "/"      # بعد الدخول -> لوحة التحكم
LOGOUT_REDIRECT_URL = "/auth/login/"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "avocat_app.middleware.idle_token.IdleTokenAuthMiddleware",  # لديك مسبقاً
    "avocat_app.middleware.request_local.RequestLocalMiddleware", # <— جديد: يضع request في threadlocal
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'avocat_yassine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",  # <— obligatoire
            ],
        },
    },
]


WSGI_APPLICATION = 'avocat_yassine.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'avocat_db',
        'USER': 'root',
        'PASSWORD': 'Bismillah@99',
        'HOST':'localhost',
        'PORT':'3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'use_unicode': True,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================
# FILE: settings extract (à ajouter dans settings.py)
# =============================
# Délais et canaux par défaut — يمكن تعديلها حسب نوع القضية أو الغرفة القضائية.
APPEAL_DEADLINE_DAYS = 30              # أجل الاستئناف الافتراضي (مدني). عدّل وفق احتياجك.
APPEAL_REMINDERS_DAYS = [7, 3, 1]      # تذكير قبل 7 و3 و1 يومًا
ALERTE_CHANNELS = ['InApp']            # أو ['Email','SMS','InApp'] حسب تكاملك
ALERTE_DEFAULT_RECIPIENT = 'Avocat responsable'

LOCALE_PATHS = [BASE_DIR / "locale"]

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.example.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'info@lrsmf.ma'
    EMAIL_HOST_PASSWORD = 'your-email-password'
