# Generated by Django 5.1.2 on 2025-10-20 22:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_interne', models.CharField(max_length=50, unique=True, verbose_name='مرجع داخلي')),
                ('reference_tribunal', models.CharField(blank=True, max_length=100, null=True, verbose_name='مرجع المحكمة')),
                ('type_affaire', models.CharField(choices=[('Pénal', 'جنائي'), ('Pénal-Flagrant', 'جنائي تلبّسي'), ('Pénal-Contravention', 'مخالفة'), ('Pénal-Routier', 'جنح السير'), ('Civil', 'مدني'), ('Location', 'كراء'), ('Famille', 'أسرة'), ('Social', 'اجتماعي'), ('Commercial', 'تجاري'), ('Autre', 'أخرى')], max_length=30, verbose_name='نوع القضية')),
                ('statut_affaire', models.CharField(choices=[('Ouverte', 'مفتوحة'), ('En audience', 'في الجلسات'), ('En délibéré', 'في المداولة'), ('Jugée', 'محكوم فيها'), ('En notification', 'قيد التبليغ'), ('En recours', 'قيد الطعن'), ('En exécution', 'قيد التنفيذ'), ('Clôturée', 'مختتمة'), ('Classée', 'محفوظة')], default='Ouverte', max_length=20, verbose_name='حالة القضية')),
                ('date_ouverture', models.DateField(verbose_name='تاريخ الفتح')),
                ('objet', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='موضوع الدعوى')),
                ('valeur_litige', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قيمة النزاع')),
                ('priorite', models.CharField(choices=[('Haute', 'مرتفعة'), ('Normale', 'عادية'), ('Basse', 'منخفضة')], default='Normale', max_length=10, verbose_name='الأولوية')),
                ('notes', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'قضية',
                'verbose_name_plural': 'قضايا',
                'db_table': 'affaire',
            },
        ),
        migrations.CreateModel(
            name='Avocat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='الاسم يجب أن يكون بالعربية.', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ\\s\\-']+$")], verbose_name='اسم المحامي')),
                ('barreau', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='هيئة الانتماء')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='هاتف')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='بريد إلكتروني')),
                ('taux_horaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعريفة بالساعة')),
            ],
            options={
                'verbose_name': 'محامٍ',
                'verbose_name_plural': 'محامون',
                'db_table': 'avocat',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='الاسم يجب أن يكون بالعربية.', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ\\s\\-']+$")], verbose_name='الاسم الكامل')),
                ('role', models.CharField(choices=[('Admin', 'مدير'), ('Avocat', 'محامٍ'), ('Assistant', 'مساعد'), ('Stagiaire', 'متدرّب'), ('Lecteur', 'قارىء')], max_length=10, verbose_name='الدور')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='هاتف')),
                ('email', models.EmailField(max_length=120, validators=[django.core.validators.EmailValidator()], verbose_name='بريد إلكتروني')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
                ('preferences_langue', models.CharField(choices=[('ar', 'العربية'), ('fr', 'الفرنسية')], default='ar', max_length=2, verbose_name='لغة التفضيل')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'مستخدمون',
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_alerte', models.CharField(choices=[('Audience', 'جلسة'), ('Echéance recours', 'أجل الطعن'), ('Exécution', 'تنفيذ'), ('Dépense', 'مصاريف'), ('Autre', 'أخرى')], max_length=20, verbose_name='نوع التنبيه')),
                ('reference_id', models.UUIDField(verbose_name='المعرّف المرتبط')),
                ('date_alerte', models.DateTimeField(verbose_name='تاريخ التنبيه')),
                ('moyen', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('InApp', 'داخل النظام')], max_length=10, verbose_name='قناة الإشعار')),
                ('destinataire', models.CharField(max_length=180, verbose_name='المرسل إليه')),
                ('message', models.TextField(validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='نص التنبيه')),
            ],
            options={
                'verbose_name': 'تنبيه',
                'verbose_name_plural': 'تنبيهات',
                'db_table': 'alerte',
                'indexes': [models.Index(fields=['date_alerte'], name='alerte_date_al_a6c5c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_audience', models.CharField(choices=[('Mise en état', 'جلسة تعيين/تهيئة'), ('Plaidoirie', 'مرافعة'), ('Débat', 'مناقشة'), ('Délibéré', 'مداولة'), ('Prononcé', 'جلسة النطق'), ('Référé', 'استعجالي'), ('Injonction', 'أمر بالأداء/إنذار'), ('Autre', 'أخرى')], max_length=20, verbose_name='نوع الجلسة')),
                ('date_audience', models.DateTimeField(verbose_name='تاريخ الجلسة')),
                ('resultat', models.CharField(blank=True, choices=[('Report', 'تأجيل'), ('Mesure ordonnée', 'اتخاذ إجراء'), ('Clôture plaidoiries', 'اختتام المرافعات'), ('Jugement prononcé', 'صدر الحكم'), ('Sans suite', 'بدون متابعة')], max_length=30, null=True, verbose_name='النتيجة')),
                ('proces_verbal', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='محضر الجلسة')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat_app.affaire', verbose_name='القضية')),
            ],
            options={
                'verbose_name': 'جلسة',
                'verbose_name_plural': 'جلسات',
                'db_table': 'audience',
                'ordering': ['-date_audience'],
            },
        ),
        migrations.CreateModel(
            name='AffaireAvocat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Responsable', 'مسؤول'), ('Collaborateur', 'مساعد'), ('Correspondant', 'مراسل'), ('Adversaire', 'خصم')], max_length=20, verbose_name='دور المحامي')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat_app.affaire')),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat_app.avocat')),
            ],
            options={
                'verbose_name': 'ربط محامٍ بقضية',
                'verbose_name_plural': 'محامو القضايا',
                'db_table': 'affaire_avocat',
            },
        ),
        migrations.AddField(
            model_name='affaire',
            name='avocat_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affaires_responsable', to='avocat_app.avocat', verbose_name='المحامي المسؤول'),
        ),
        migrations.AddField(
            model_name='affaire',
            name='avocats',
            field=models.ManyToManyField(related_name='affaires', through='avocat_app.AffaireAvocat', to='avocat_app.avocat', verbose_name='محامون'),
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_decision', models.CharField(max_length=80, verbose_name='رقم الحكم/القرار')),
                ('date_prononce', models.DateField(verbose_name='تاريخ النطق')),
                ('formation', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='الهيئة/القاضي')),
                ('resumé', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='ملخص')),
                ('susceptible_recours', models.BooleanField(default=True, verbose_name='قابل للطعن')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat_app.affaire', verbose_name='القضية')),
            ],
            options={
                'verbose_name': 'حكم/قرار',
                'verbose_name_plural': 'أحكام/قرارات',
                'db_table': 'decision',
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_depense', models.CharField(choices=[('Frais de justice', 'رسوم قضائية'), ('Huissier', 'مفوض قضائي'), ('Expertise', 'خبرة'), ('Déplacement', 'تنقل'), ('Frais de dossier', 'مصاريف ملف'), ('Autre', 'أخرى')], max_length=20, verbose_name='نوع المصروف')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('date_depense', models.DateField(verbose_name='تاريخ الصرف')),
                ('beneficiaire', models.CharField(blank=True, max_length=180, null=True, validators=[django.core.validators.RegexValidator(message='الاسم يجب أن يكون بالعربية.', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ\\s\\-']+$")], verbose_name='المستفيد')),
                ('piece', models.FileField(blank=True, null=True, upload_to='depenses/', verbose_name='مرفق (ملف)')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat_app.affaire', verbose_name='القضية')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'مصاريف',
                'db_table': 'depense',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_execution', models.CharField(choices=[('Monétaire', 'تنفيذ مالي'), ('Expulsion/Évacuation', 'إفراغ/إخلاء'), ('Saisie', 'حجز'), ('Autre', 'تنفيذ آخر')], max_length=30, verbose_name='نوع التنفيذ')),
                ('date_demande', models.DateField(verbose_name='تاريخ الطلب')),
                ('statut', models.CharField(choices=[('En attente', 'بانتظار'), ('En cours', 'جارٍ'), ('Suspendu', 'موقوف'), ('Achevé', 'منتهٍ'), ('Infructueux', 'متعذّر')], default='En attente', max_length=15, verbose_name='حالة التنفيذ')),
                ('depot_caisse_barreau', models.BooleanField(default=False, verbose_name='إيداع بصندوق الهيئة')),
                ('date_demande_liquidation', models.DateField(blank=True, null=True, verbose_name='تاريخ طلب التصفية')),
                ('proces_verbal_refus', models.CharField(blank=True, max_length=120, null=True, verbose_name='مرجع محضر الامتناع')),
                ('date_pv_refus', models.DateField(blank=True, null=True, verbose_name='تاريخ محضر الامتناع')),
                ('contrainte_par_corps_num', models.CharField(blank=True, max_length=120, null=True, verbose_name='رقم ملف الإكراه البدني')),
                ('date_contrainte', models.DateField(blank=True, null=True, verbose_name='تاريخ الإحالة على الإكراه')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat_app.decision', verbose_name='الحكم/القرار')),
            ],
            options={
                'verbose_name': 'تنفيذ',
                'verbose_name_plural': 'تنفيذات',
                'db_table': 'execution',
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expert_nom', models.CharField(max_length=180, validators=[django.core.validators.RegexValidator(message='الاسم يجب أن يكون بالعربية.', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ\\s\\-']+$")], verbose_name='اسم الخبير')),
                ('date_ordonnee', models.DateField(verbose_name='تاريخ الأمر')),
                ('date_depot', models.DateField(blank=True, null=True, verbose_name='تاريخ الإيداع')),
                ('contre_expertise', models.BooleanField(default=False, verbose_name='خبرة مضادّة')),
                ('rapport', models.FileField(blank=True, null=True, upload_to='expertises/', verbose_name='تقرير (ملف)')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat_app.affaire', verbose_name='القضية')),
            ],
            options={
                'verbose_name': 'خبرة',
                'verbose_name_plural': 'خبرات',
                'db_table': 'expertise',
            },
        ),
        migrations.CreateModel(
            name='Juridiction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=180, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='اسم الجهة')),
                ('ville', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='المدينة')),
                ('type', models.CharField(choices=[('Tribunal de Première Instance', 'المحكمة الابتدائية'), ('Cour d’Appel', 'محكمة الاستئناف'), ('Cour de Cassation', 'محكمة النقض'), ('Autre', 'جهة أخرى')], max_length=40, verbose_name='النوع')),
            ],
            options={
                'verbose_name': 'جهة قضائية',
                'verbose_name_plural': 'جهات قضائية',
                'db_table': 'juridiction',
                'indexes': [models.Index(fields=['ville'], name='juridiction_ville_d9fba5_idx')],
            },
        ),
        migrations.AddField(
            model_name='affaire',
            name='juridiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.juridiction', verbose_name='المحكمة'),
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_mesure', models.CharField(choices=[('Enquête', 'بحث'), ('Expertise', 'خبرة'), ('Inspection', 'معاينة'), ('Interrogatoire', 'استجواب'), ('Témoignage', 'شهادة'), ('Confrontation', 'مواجهة'), ('Autre', 'إجراء آخر')], max_length=20, verbose_name='نوع الإجراء')),
                ('statut', models.CharField(choices=[('Ordonnée', 'مأمور بها'), ('En cours', 'جارٍ'), ('Déposée', 'أودِع التقرير'), ('Contre-expertise', 'خبرة مضادّة'), ('Clôturée', 'مختتمة')], default='Ordonnée', max_length=20, verbose_name='حالة الإجراء')),
                ('notes', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='ملاحظات')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat_app.audience', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'إجراء',
                'verbose_name_plural': 'إجراءات',
                'db_table': 'mesure',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('demande_numero', models.CharField(max_length=80, verbose_name='رقم طلب التبليغ')),
                ('date_depot_demande', models.DateField(verbose_name='تاريخ إيداع الطلب')),
                ('dossier_notification_numero', models.CharField(blank=True, max_length=80, null=True, verbose_name='رقم ملف التبليغ')),
                ('huissier_nom', models.CharField(blank=True, max_length=180, null=True, validators=[django.core.validators.RegexValidator(message='الاسم يجب أن يكون بالعربية.', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ\\s\\-']+$")], verbose_name='اسم المفوض القضائي')),
                ('date_remise_huissier', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم للمفوض')),
                ('date_signification', models.DateField(blank=True, null=True, verbose_name='تاريخ التبليغ')),
                ('preuve', models.FileField(blank=True, null=True, upload_to='notifications/', verbose_name='محضر/إثبات (ملف)')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat_app.decision', verbose_name='الحكم/القرار')),
            ],
            options={
                'verbose_name': 'تبليغ',
                'verbose_name_plural': 'تبليغات',
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_partie', models.CharField(choices=[('Demandeur', 'مدعٍ'), ('Défendeur', 'مدعى عليه'), ('Plagnant', 'شاكي'), ('Prévenu', 'متّهم'), ('Intimé', 'مستأنف عليه'), ('Appelant', 'مستأنِف'), ('Témoin', 'شاهد'), ('Expert', 'خبير'), ('Autre', 'غير ذلك')], max_length=20, verbose_name='صفة الطرف')),
                ('nom_complet', models.CharField(max_length=180, validators=[django.core.validators.RegexValidator(message='الاسم يجب أن يكون بالعربية.', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ\\s\\-']+$")], verbose_name='الاسم الكامل')),
                ('cin_ou_rc', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التعريف/السجل التجاري')),
                ('adresse', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='العنوان')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='هاتف')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='بريد إلكتروني')),
                ('representant_legal', models.CharField(blank=True, max_length=180, null=True, validators=[django.core.validators.RegexValidator(message='الاسم يجب أن يكون بالعربية.', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ\\s\\-']+$")], verbose_name='الممثل القانوني')),
                ('avocat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avocat_app.avocat', verbose_name='محامي الطرف')),
            ],
            options={
                'verbose_name': 'طرف',
                'verbose_name_plural': 'أطراف',
                'db_table': 'partie',
            },
        ),
        migrations.CreateModel(
            name='AffairePartie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_dans_affaire', models.CharField(choices=[('Demandeur', 'مدعٍ'), ('Défendeur', 'مدعى عليه'), ('Plagnant', 'شاكي'), ('Prévenu', 'متّهم'), ('Intimé', 'مستأنف عليه'), ('Appelant', 'مستأنِف'), ('Autre', 'غير ذلك')], max_length=20, verbose_name='الدور في القضية')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat_app.affaire')),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat_app.partie')),
            ],
            options={
                'verbose_name': 'ربط طرف بقضية',
                'verbose_name_plural': 'أطراف القضايا',
                'db_table': 'affaire_partie',
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=180, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='عنوان المرفق')),
                ('type_piece', models.CharField(choices=[('PDF', 'PDF'), ('Image', 'صورة'), ('Doc', 'مستند'), ('Audio', 'صوت'), ('Autre', 'أخرى')], max_length=10, verbose_name='نوع الملف')),
                ('fichier', models.FileField(upload_to='pieces/', verbose_name='ملف')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='avocat_app.affaire', verbose_name='القضية')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'مرفقات',
                'db_table': 'piece_jointe',
            },
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_recette', models.CharField(choices=[('Provision', 'تسبيق'), ('Honoraires', 'أتعاب'), ('Remboursement frais', 'استرجاع مصاريف'), ('Condamnation', 'مبالغ محكوم بها'), ('Autre', 'أخرى')], max_length=25, verbose_name='نوع الدخل')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('date_recette', models.DateField(verbose_name='تاريخ التحصيل')),
                ('source', models.CharField(blank=True, max_length=180, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='المصدر')),
                ('piece', models.FileField(blank=True, null=True, upload_to='recettes/', verbose_name='مرفق (ملف)')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat_app.affaire', verbose_name='القضية')),
            ],
            options={
                'verbose_name': 'دخل/تحصيل',
                'verbose_name_plural': 'مداخيل',
                'db_table': 'recette',
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=180, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='عنوان المهمة')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='وصف')),
                ('echeance', models.DateTimeField(blank=True, null=True, verbose_name='موعد الاستحقاق')),
                ('statut', models.CharField(choices=[('A faire', 'للتنفيذ'), ('En cours', 'جارٍ'), ('En attente', 'بانتظار'), ('Terminé', 'منجز')], default='A faire', max_length=12, verbose_name='الحالة')),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avocat_app.affaire', verbose_name='القضية')),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avocat_app.utilisateur', verbose_name='مكلّف')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'مهام',
                'db_table': 'tache',
            },
        ),
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=120, verbose_name='الإجراء')),
                ('objet', models.CharField(max_length=120, verbose_name='الكيان')),
                ('objet_id', models.UUIDField(verbose_name='معرّف الكيان')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('details', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='تفاصيل')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avocat_app.utilisateur', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجلّ نشاط',
                'verbose_name_plural': 'سجلّ الأنشطة',
                'db_table': 'journal_activite',
            },
        ),
        migrations.CreateModel(
            name='VoieDeRecours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_recours', models.CharField(choices=[('Appel', 'استئناف'), ('Opposition', 'تعرض'), ('Cassation', 'نقض'), ('Rétractation', 'مراجعة'), ('Autre', 'طعن آخر')], max_length=20, verbose_name='نوع الطعن')),
                ('date_depot', models.DateField(verbose_name='تاريخ الإيداع')),
                ('numero_recours', models.CharField(blank=True, max_length=80, null=True, verbose_name='رقم ملف الطعن')),
                ('statut', models.CharField(choices=[('En cours', 'جارٍ'), ('Rejeté', 'مرفوض'), ('Reçu', 'مقبول شكلاً'), ('Jugé', 'محكوم'), ('Clôturé', 'مختتم')], default='En cours', max_length=15, verbose_name='الحالة')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat_app.decision', verbose_name='الحكم/القرار')),
                ('juridiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.juridiction', verbose_name='الجهة الناظرة')),
            ],
            options={
                'verbose_name': 'طريق طعن',
                'verbose_name_plural': 'طرق الطعن',
                'db_table': 'voie_de_recours',
            },
        ),
        migrations.AddIndex(
            model_name='audience',
            index=models.Index(fields=['date_audience'], name='audience_date_au_977815_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='affaireavocat',
            unique_together={('affaire', 'avocat', 'role')},
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['numero_decision'], name='decision_numero__a50d88_idx'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['date_depense'], name='depense_date_de_559726_idx'),
        ),
        migrations.AddIndex(
            model_name='affaire',
            index=models.Index(fields=['reference_interne'], name='affaire_referen_6533c2_idx'),
        ),
        migrations.AddIndex(
            model_name='affaire',
            index=models.Index(fields=['reference_tribunal'], name='affaire_referen_f1ae30_idx'),
        ),
        migrations.AddIndex(
            model_name='affaire',
            index=models.Index(fields=['type_affaire', 'statut_affaire'], name='affaire_type_af_40bf86_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['date_signification'], name='notificatio_date_si_7c039b_idx'),
        ),
        migrations.AddIndex(
            model_name='partie',
            index=models.Index(fields=['nom_complet'], name='partie_nom_com_4b98bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='affairepartie',
            unique_together={('affaire', 'partie', 'role_dans_affaire')},
        ),
        migrations.AddIndex(
            model_name='recette',
            index=models.Index(fields=['date_recette'], name='recette_date_re_c4b8e4_idx'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['echeance'], name='tache_echeanc_f77054_idx'),
        ),
        migrations.AddIndex(
            model_name='journalactivite',
            index=models.Index(fields=['date_action'], name='journal_act_date_ac_8a714d_idx'),
        ),
    ]
