# Generated by Django 5.1.2 on 2025-10-21 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('CREATE', 'إنشاء'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('LOGIN', 'دخول'), ('LOGOUT', 'خروج'), ('ATTACH', 'إرفاق ملف'), ('EMAIL', 'إرسال بريد'), ('SMS', 'إرسال SMS'), ('EXPORT', 'تصدير'), ('IMPORT', 'استيراد'), ('OTHER', 'أخرى')], max_length=16)),
                ('app_label', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('object_pk', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('token_id', models.IntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['app_label', 'model', 'object_pk'], name='avocat_app__app_lab_79b719_idx'), models.Index(fields=['actor', 'action', 'timestamp'], name='avocat_app__actor_i_157f27_idx')],
            },
        ),
    ]
