# Generated by Django 5.1.2 on 2025-10-21 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='رمز المصادقة')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('date_expiration', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat_app.utilisateur', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز مصادقة',
                'verbose_name_plural': 'رموز المصادقة',
                'db_table': 'auth_token',
                'indexes': [models.Index(fields=['date_expiration'], name='auth_token_date_ex_da3f01_idx')],
            },
        ),
    ]
