# Generated by Django 5.1.2 on 2025-10-21 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0003_authtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='authtoken',
            name='auth_token_date_ex_da3f01_idx',
        ),
        migrations.AddField(
            model_name='authtoken',
            name='ip_addr',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخر نشاط'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='user_agent',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['token'], name='avocat_app__token_d1752e_idx'),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['utilisateur', 'is_active'], name='avocat_app__utilisa_0f51fd_idx'),
        ),
        migrations.AlterModelTable(
            name='authtoken',
            table=None,
        ),
    ]
