# Generated by Django 5.1.2 on 2025-10-21 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0004_remove_authtoken_auth_token_date_ex_da3f01_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='authtoken',
            name='avocat_app__utilisa_0f51fd_idx',
        ),
        migrations.RenameField(
            model_name='authtoken',
            old_name='utilisateur',
            new_name='user',
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['user', 'is_active'], name='avocat_app__user_id_4d6a0d_idx'),
        ),
    ]
