# Generated by Django 5.1.2 on 2025-10-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0004_alter_statutexecution_id_alter_typealerte_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeaffaire',
            name='code',
            field=models.CharField(default=1, max_length=4, unique=True, verbose_name='الرمز'),
            preserve_default=False,
        ),
    ]
