# Generated by Django 5.1.2 on 2025-10-26 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0005_typeaffaire_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='juridiction',
            name='juridiction_ville_d9fba5_idx',
        ),
        migrations.RenameField(
            model_name='juridiction',
            old_name='parent',
            new_name='idTribunalParent',
        ),
        migrations.RemoveField(
            model_name='juridiction',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='juridiction',
            name='ville',
        ),
        migrations.AddField(
            model_name='juridiction',
            name='adressetribunal_ar',
            field=models.CharField(default='', max_length=180, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='العنوان بالعربية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juridiction',
            name='adressetribunal_fr',
            field=models.CharField(default=1, max_length=180, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='العنوان بالفرنسية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juridiction',
            name='nomtribunal_ar',
            field=models.CharField(default='', max_length=180, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='الاسم بالعربية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juridiction',
            name='nomtribunal_fr',
            field=models.CharField(default='', max_length=180, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='الاسم بالفرنسية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juridiction',
            name='telephonetribunal',
            field=models.CharField(default='', max_length=180, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juridiction',
            name='villetribunal_ar',
            field=models.CharField(default='', max_length=180, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='المدينة بالعربية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juridiction',
            name='villetribunal_fr',
            field=models.CharField(default='', max_length=180, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='المدينة بالفرنسية'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='juridiction',
            index=models.Index(fields=['villetribunal_ar'], name='juridiction_villetr_34e120_idx'),
        ),
    ]
