# Generated by Django 5.1.2 on 2025-10-26 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0006_remove_juridiction_juridiction_ville_d9fba5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typejuridiction',
            name='code_type',
            field=models.CharField(default='', max_length=180, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='الرمز'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typejuridiction',
            name='description',
            field=models.CharField(default='', max_length=580, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='الوصف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typejuridiction',
            name='niveau',
            field=models.CharField(default='', max_length=180, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='المستوى'),
            preserve_default=False,
        ),
    ]
