# Generated by Django 5.1.2 on 2025-10-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0007_typejuridiction_code_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juridiction',
            name='degre',
        ),
    ]
