# Generated by Django 5.1.2 on 2025-10-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0008_remove_juridiction_degre'),
    ]

    operations = [
        migrations.AddField(
            model_name='juridiction',
            name='code',
            field=models.CharField(default='', max_length=180, verbose_name='الرمز'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='juridiction',
            name='adressetribunal_fr',
            field=models.CharField(max_length=180, verbose_name='العنوان بالفرنسية'),
        ),
        migrations.AlterField(
            model_name='juridiction',
            name='nomtribunal_fr',
            field=models.CharField(max_length=180, verbose_name='الاسم بالفرنسية'),
        ),
        migrations.AlterField(
            model_name='juridiction',
            name='telephonetribunal',
            field=models.CharField(max_length=180, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='juridiction',
            name='villetribunal_fr',
            field=models.CharField(max_length=180, verbose_name='المدينة بالفرنسية'),
        ),
    ]
