# Generated by Django 5.1.2 on 2025-10-26 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0009_juridiction_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juridiction',
            name='adressetribunal_ar',
            field=models.CharField(blank=True, max_length=180, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='العنوان بالعربية'),
        ),
        migrations.AlterField(
            model_name='juridiction',
            name='adressetribunal_fr',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='العنوان بالفرنسية'),
        ),
        migrations.AlterField(
            model_name='juridiction',
            name='nomtribunal_ar',
            field=models.CharField(blank=True, max_length=180, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='الاسم بالعربية'),
        ),
        migrations.AlterField(
            model_name='juridiction',
            name='nomtribunal_fr',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='الاسم بالفرنسية'),
        ),
        migrations.AlterField(
            model_name='juridiction',
            name='telephonetribunal',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='juridiction',
            name='villetribunal_ar',
            field=models.CharField(blank=True, max_length=180, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='المدينة بالعربية'),
        ),
        migrations.AlterField(
            model_name='juridiction',
            name='villetribunal_fr',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='المدينة بالفرنسية'),
        ),
    ]
