# Generated by Django 5.1.2 on 2025-10-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0010_alter_juridiction_adressetribunal_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juridiction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
