# Generated by Django 5.1.2 on 2025-10-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0011_alter_juridiction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juridiction',
            old_name='idTribunalParent',
            new_name='TribunalParent',
        ),
    ]
