# Generated by Django 5.1.2 on 2026-02-19 22:40

import avocat_app.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0012_rename_idtribunalparent_juridiction_tribunalparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='avocat_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affaires_responsable', to='avocat_app.avocat', verbose_name='المحامي المسؤول'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='juridiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.juridiction', verbose_name='المحكمة'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='statut_affaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.statutaffaire', verbose_name='حالة القضية'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='type_affaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.typeaffaire', verbose_name='نوع القضية'),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.typealerte', verbose_name='نوع التنبيه'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='resultat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.resultataudience', verbose_name='النتيجة'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='type_audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.typeaudience', verbose_name='نوع الجلسة'),
        ),
        migrations.AlterField(
            model_name='avocat',
            name='barreau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.barreau', verbose_name='الهيئة'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='piece',
            field=models.FileField(blank=True, null=True, upload_to='depenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'mp3', 'wav', 'ogg'], message='نوع الملف غير مسموح. الأنواع المسموحة: %(allowed_extensions)s'), avocat_app.models.validate_file_size], verbose_name='مرفق (ملف)'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='type_depense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.typedepense', verbose_name='نوع المصروف'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.statutexecution', verbose_name='حالة التنفيذ'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='type_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.typeexecution', verbose_name='نوع التنفيذ'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='specialite',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='الاسم يجب أن يكون بالعربية.', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ\\s\\-']+$")], verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='rapport',
            field=models.FileField(blank=True, null=True, upload_to='expertises/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'mp3', 'wav', 'ogg'], message='نوع الملف غير مسموح. الأنواع المسموحة: %(allowed_extensions)s'), avocat_app.models.validate_file_size], verbose_name='تقرير (ملف)'),
        ),
        migrations.AlterField(
            model_name='juridiction',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.typejuridiction', verbose_name='نوع المحكمة'),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.statutmesure', verbose_name='حالة الإجراء'),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='type_mesure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.typemesure', verbose_name='نوع الإجراء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='preuve',
            field=models.FileField(blank=True, null=True, upload_to='notifications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'mp3', 'wav', 'ogg'], message='نوع الملف غير مسموح. الأنواع المسموحة: %(allowed_extensions)s'), avocat_app.models.validate_file_size], verbose_name='محضر/إثبات (ملف)'),
        ),
        migrations.AlterField(
            model_name='piecejointe',
            name='fichier',
            field=models.FileField(upload_to='pieces/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'mp3', 'wav', 'ogg'], message='نوع الملف غير مسموح. الأنواع المسموحة: %(allowed_extensions)s'), avocat_app.models.validate_file_size], verbose_name='ملف'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='piece',
            field=models.FileField(blank=True, null=True, upload_to='recettes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'mp3', 'wav', 'ogg'], message='نوع الملف غير مسموح. الأنواع المسموحة: %(allowed_extensions)s'), avocat_app.models.validate_file_size], verbose_name='مرفق (ملف)'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='type_recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.typerecette', verbose_name='نوع الدخل'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.statuttache', verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.roleutilisateur', verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='voiederecours',
            name='juridiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.juridiction', verbose_name='المحكمة'),
        ),
        migrations.AlterField(
            model_name='voiederecours',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.statutrecours', verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='voiederecours',
            name='type_recours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.typerecours', verbose_name='نوع الطعن'),
        ),
    ]
