# Generated by Django 5.1.2 on 2026-02-21 01:25

import avocat_app.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0013_alter_affaire_avocat_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affaire',
            name='phase',
            field=models.CharField(choices=[('PRELIMINAIRE', 'المرحلة التمهيدية'), ('PREMIERE_INSTANCE', 'المحكمة الابتدائية'), ('APPEL', 'محكمة الاستئناف'), ('CASSATION', 'محكمة النقض'), ('EXECUTION', 'التنفيذ'), ('CLOTURE', 'مقفلة')], default='PRELIMINAIRE', max_length=20, verbose_name='المرحلة'),
        ),
        migrations.AddField(
            model_name='typerecours',
            name='delai_legal_jours',
            field=models.PositiveIntegerField(default=30, verbose_name='الأجل القانوني (أيام)'),
        ),
        migrations.AddField(
            model_name='typerecours',
            name='domaine',
            field=models.CharField(choices=[('civil', 'مدني'), ('penal', 'جنائي'), ('commercial', 'تجاري'), ('administratif', 'إداري'), ('social', 'اجتماعي')], default='civil', max_length=20, verbose_name='المجال'),
        ),
        migrations.AddField(
            model_name='voiederecours',
            name='date_echeance_recours',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء أجل الطعن'),
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تم التحديث في')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('phase', models.CharField(choices=[('PRELIMINAIRE', 'المرحلة التمهيدية'), ('PREMIERE_INSTANCE', 'المحكمة الابتدائية'), ('APPEL', 'محكمة الاستئناف'), ('CASSATION', 'محكمة النقض'), ('EXECUTION', 'التنفيذ'), ('CLOTURE', 'مقفلة')], max_length=20, verbose_name='المرحلة')),
                ('nom_document', models.CharField(max_length=180, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='اسم الوثيقة')),
                ('nom_document_fr', models.CharField(blank=True, default='', max_length=180, verbose_name='nom du document')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='إلزامي')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='وصف')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('type_affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avocat_app.typeaffaire', verbose_name='نوع القضية')),
            ],
            options={
                'verbose_name': 'متطلب وثائقي',
                'verbose_name_plural': 'متطلبات وثائقية',
                'db_table': 'document_requirement',
                'ordering': ['phase', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='TypeAvertissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تم التحديث في')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('libelle', models.CharField(max_length=180, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='الاسم')),
                ('libelle_fr', models.CharField(blank=True, default='', max_length=180, verbose_name='nom en français')),
                ('delai_legal_jours', models.PositiveIntegerField(default=15, verbose_name='الأجل القانوني (أيام)')),
                ('domaine', models.CharField(choices=[('civil', 'مدني'), ('penal', 'جنائي'), ('commercial', 'تجاري'), ('administratif', 'إداري'), ('social', 'اجتماعي')], default='civil', max_length=20, verbose_name='المجال')),
                ('base_legale', models.CharField(blank=True, default='', max_length=255, verbose_name='السند القانوني')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('libelle',), name='uniq_typeavertissement_libelle_alive')],
            },
        ),
        migrations.CreateModel(
            name='Avertissement',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تم التحديث في')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_envoi', models.DateField(verbose_name='تاريخ الإرسال')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الأجل')),
                ('destinataire_nom', models.CharField(max_length=180, validators=[django.core.validators.RegexValidator(message='الاسم يجب أن يكون بالعربية.', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ\\s\\-']+$")], verbose_name='اسم المرسل إليه')),
                ('destinataire_adresse', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='عنوان المرسل إليه')),
                ('moyen_envoi', models.CharField(choices=[('huissier', 'مفوض قضائي'), ('poste', 'البريد المضمون'), ('main', 'تسليم باليد'), ('email', 'بريد إلكتروني')], default='huissier', max_length=20, verbose_name='وسيلة الإرسال')),
                ('numero_suivi', models.CharField(blank=True, max_length=80, null=True, verbose_name='رقم التتبع')),
                ('resultat', models.CharField(choices=[('en_attente', 'في الانتظار'), ('reponse', 'تم الرد'), ('sans_reponse', 'بدون رد'), ('partielle', 'استجابة جزئية')], default='en_attente', max_length=20, verbose_name='النتيجة')),
                ('date_reponse', models.DateField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('objet_avertissement', models.TextField(validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='موضوع الإنذار')),
                ('document', models.FileField(blank=True, null=True, upload_to='avertissements/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'mp3', 'wav', 'ogg'], message='نوع الملف غير مسموح. الأنواع المسموحة: %(allowed_extensions)s'), avocat_app.models.validate_file_size], verbose_name='نسخة الإنذار')),
                ('preuve_envoi', models.FileField(blank=True, null=True, upload_to='avertissements/preuves/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'mp3', 'wav', 'ogg'], message='نوع الملف غير مسموح. الأنواع المسموحة: %(allowed_extensions)s'), avocat_app.models.validate_file_size], verbose_name='إثبات الإرسال')),
                ('notes_reponse', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='المرجو إدخال محتوى باللغة العربية (يمكن استعمال الأرقام وبعض الرموز البسيطة).', regex="^[\u0600-ۿݐ-ݿࢠ-ࣿ0-9\\s\\-_'.,()\\/:]+$")], verbose_name='ملاحظات على الرد')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocat_app.affaire', verbose_name='القضية')),
                ('type_avertissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocat_app.typeavertissement', verbose_name='نوع الإنذار')),
            ],
            options={
                'verbose_name': 'إنذار',
                'verbose_name_plural': 'إنذارات',
                'db_table': 'avertissement',
                'ordering': ['-date_envoi'],
                'indexes': [models.Index(fields=['date_envoi'], name='avertisseme_date_en_049b29_idx'), models.Index(fields=['date_echeance'], name='avertisseme_date_ec_66d540_idx')],
            },
        ),
    ]
