# Generated by Django 5.1.2 on 2026-02-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0017_mahakimsyncresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='juridiction',
            name='id_mahakim',
            field=models.CharField(blank=True, help_text='المعرف الرقمي للمحكمة في بوابة mahakim.ma', max_length=20, null=True, verbose_name='معرف محاكم.ما'),
        ),
    ]
