# Generated by Django 5.1.2 on 2026-02-27 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0018_juridiction_id_mahakim'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahakimsyncresult',
            name='parties_json',
            field=models.JSONField(blank=True, null=True, verbose_name='الأطراف المستخرجة'),
        ),
        migrations.AddField(
            model_name='mahakimsyncresult',
            name='procedures_json',
            field=models.JSONField(blank=True, null=True, verbose_name='الإجراءات المستخرجة'),
        ),
        migrations.AddField(
            model_name='mahakimsyncresult',
            name='sync_type',
            field=models.CharField(choices=[('dossier', 'ملف/محضر/شكاية'), ('sessions', 'جدول الجلسات')], default='dossier', max_length=20, verbose_name='نوع المزامنة'),
        ),
        migrations.AlterField(
            model_name='mahakimsyncresult',
            name='affaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahakim_syncs', to='avocat_app.affaire', verbose_name='القضية'),
        ),
    ]
