# Generated by Django 5.1.2 on 2026-02-27 07:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0019_mahakim_sync_type_procedures_parties'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContumaceRecord',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تم التحديث في')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cour_appel', models.CharField(max_length=200, verbose_name='محكمة الاستئناف')),
                ('numero_dossier', models.CharField(max_length=100, verbose_name='رقم الملف')),
                ('nom_accuse', models.CharField(max_length=200, verbose_name='اسم المتهم')),
                ('nom_pere', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الأب')),
                ('nom_mere', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الأم')),
                ('numero_carte', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم البطاقة')),
                ('details_text', models.TextField(blank=True, null=True, verbose_name='التفاصيل')),
                ('date_sync', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المزامنة')),
            ],
            options={
                'verbose_name': 'سجل المسطرة الغيابية',
                'verbose_name_plural': 'سجلات المسطرة الغيابية',
                'db_table': 'contumace_record',
                'ordering': ['-date_sync'],
                'unique_together': {('numero_dossier', 'cour_appel')},
            },
        ),
    ]
