# Generated by Django 5.1.2 on 2026-02-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0021_add_commercial_administrative_courts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCalculatorCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('options_tree', models.JSONField(default=dict, verbose_name='شجرة الخيارات')),
                ('date_sync', models.DateTimeField(auto_now=True, verbose_name='تاريخ المزامنة')),
            ],
            options={
                'verbose_name': 'ذاكرة حاسبة الرسوم',
                'db_table': 'tax_calculator_cache',
            },
        ),
    ]
