# Generated by Django 5.1.2 on 2026-05-11 12:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0022_tax_calculator_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تم التحديث في')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120, verbose_name='اسم القالب')),
                ('kind', models.CharField(choices=[('audience_j1', 'تذكير بجلسة (يوم قبل)'), ('audience_j0', 'تذكير بجلسة (اليوم)'), ('decision_rendue', 'إشعار بصدور حكم'), ('piece_manquante', 'طلب وثيقة'), ('rdv', 'تأكيد موعد'), ('autre', 'أخرى')], default='audience_j1', max_length=30, verbose_name='النوع')),
                ('body', models.TextField(help_text='يمكن استعمال المتغيرات: {{client}} {{ref}} {{tribunal}} {{date}} {{heure}} {{avocat}}', verbose_name='نص الرسالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('twilio_content_sid', models.CharField(blank=True, help_text='إذا كانت Twilio تتطلب قالب معتمد (Business)', max_length=64, null=True, verbose_name='Twilio Content SID')),
            ],
            options={
                'verbose_name': 'قالب واتساب',
                'verbose_name_plural': 'قوالب واتساب',
                'db_table': 'whatsapp_template',
                'ordering': ['kind', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تم التحديث في')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_number', models.CharField(help_text='بصيغة E.164 (+212...)', max_length=30, verbose_name='رقم المستلم')),
                ('to_name', models.CharField(blank=True, max_length=180, null=True, verbose_name='اسم المستلم')),
                ('body', models.TextField(verbose_name='نص الرسالة المُرسلة')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('sent', 'تم الإرسال'), ('delivered', 'تم التسليم'), ('read', 'تمت القراءة'), ('failed', 'فشل الإرسال'), ('dry_run', 'محاكاة (بدون إرسال)')], default='pending', max_length=20, verbose_name='الحالة')),
                ('twilio_sid', models.CharField(blank=True, max_length=64, null=True, verbose_name='معرف Twilio')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='avocat_app.affaire', verbose_name='القضية')),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='avocat_app.audience', verbose_name='الجلسة')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avocat_app.whatsapptemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'رسالة واتساب',
                'verbose_name_plural': 'رسائل واتساب',
                'db_table': 'whatsapp_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='whatsapp_me_status_e526fc_idx'), models.Index(fields=['to_number'], name='whatsapp_me_to_numb_dd9942_idx'), models.Index(fields=['-created_at'], name='whatsapp_me_created_1f3738_idx')],
            },
        ),
    ]
