# Generated by Django 5.1.2 on 2026-05-11 13:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0023_whatsapptemplate_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='juridiction',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude (ex: 33.589886)', max_digits=9, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='juridiction',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude (ex: -7.603869)', max_digits=9, null=True, verbose_name='خط الطول'),
        ),
        migrations.CreateModel(
            name='DecisionAnalysis',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تم التحديث في')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_text', models.TextField(blank=True, help_text="Texte source soumis à l'IA (extrait du PDF ou saisi).", null=True, verbose_name='النص المصدر')),
                ('resume_ar', models.TextField(blank=True, null=True, verbose_name='ملخص بالعربية')),
                ('resume_fr', models.TextField(blank=True, null=True, verbose_name='Résumé en français')),
                ('decision_essentielle', models.TextField(blank=True, null=True, verbose_name='القرار الجوهري')),
                ('parties_extraites', models.JSONField(blank=True, help_text='[{nom, role}]', null=True, verbose_name='الأطراف المستخرجة')),
                ('motifs', models.JSONField(blank=True, help_text='[{titre, contenu}]', null=True, verbose_name='الحيثيات')),
                ('delai_appel_jours', models.IntegerField(blank=True, null=True, verbose_name='أجل الاستئناف (أيام)')),
                ('dates_importantes', models.JSONField(blank=True, help_text='[{label, date_iso}]', null=True, verbose_name='تواريخ مهمة')),
                ('raw_response', models.TextField(blank=True, null=True, verbose_name='الاستجابة الخام')),
                ('model_used', models.CharField(blank=True, max_length=64, null=True, verbose_name='النموذج')),
                ('is_dry_run', models.BooleanField(default=False, verbose_name='محاكاة (بدون استدعاء API)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التحليل')),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='avocat_app.decision', verbose_name='الحكم')),
            ],
            options={
                'verbose_name': 'تحليل الحكم',
                'verbose_name_plural': 'تحاليل الأحكام',
                'db_table': 'decision_analysis',
                'ordering': ['-generated_at'],
            },
        ),
    ]
