# Generated by Django 5.1.2 on 2026-05-11 13:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0024_juridiction_latitude_juridiction_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortailAccess',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تم التحديث في')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=80, unique=True, verbose_name='رمز الوصول')),
                ('expires_at', models.DateTimeField(verbose_name='ينتهي في')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تم الاستعمال في')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True, verbose_name='User Agent')),
                ('revoked', models.BooleanField(default=False, verbose_name='ملغى')),
            ],
            options={
                'verbose_name': 'وصول إلى البوابة',
                'verbose_name_plural': 'وصولات إلى البوابة',
                'db_table': 'portail_access',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='decisionanalysis',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vecteur de similarité sémantique (list[float]).', null=True, verbose_name='التضمين'),
        ),
        migrations.AddField(
            model_name='decisionanalysis',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='نموذج التضمين'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='direction',
            field=models.CharField(choices=[('outbound', 'صادر'), ('inbound', 'وارد')], default='outbound', max_length=10, verbose_name='الاتجاه'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'في الانتظار'), ('sent', 'تم الإرسال'), ('delivered', 'تم التسليم'), ('read', 'تمت القراءة'), ('failed', 'فشل الإرسال'), ('dry_run', 'محاكاة (بدون إرسال)'), ('received', 'وارد')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['direction'], name='whatsapp_me_directi_426062_idx'),
        ),
        migrations.AddField(
            model_name='portailaccess',
            name='partie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portail_accesses', to='avocat_app.partie', verbose_name='الطرف'),
        ),
        migrations.AddIndex(
            model_name='portailaccess',
            index=models.Index(fields=['token'], name='portail_acc_token_f9b03e_idx'),
        ),
        migrations.AddIndex(
            model_name='portailaccess',
            index=models.Index(fields=['partie', 'revoked'], name='portail_acc_partie__57f4ea_idx'),
        ),
    ]
