# Generated by Django 5.1.2 on 2026-05-19 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0026_cabinetparams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='resultat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='avocat_app.resultataudience', verbose_name='النتيجة'),
        ),
        migrations.AlterField(
            model_name='cabinetparams',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='أُنشئ في'),
        ),
        migrations.AlterField(
            model_name='cabinetparams',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cabinetparams',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟'),
        ),
        migrations.AlterField(
            model_name='cabinetparams',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تم التحديث في'),
        ),
    ]
