# Generated by Django 5.1.2 on 2026-05-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0027_alter_audience_resultat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codecategorieaffaire',
            name='type_juridiction_initiale',
            field=models.ForeignKey(blank=True, help_text='نوع المحكمة المختصة ابتدائيًا لهذه الفئة (مثلاً TPI، TC، TA، CA مباشرة...)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_initiales', to='avocat_app.typejuridiction', verbose_name='نوع المحكمة الأولى'),
        ),
    ]
