# Generated by Django 5.1.2 on 2026-06-03 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0028_codecategorieaffaire_type_juridiction_initiale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('op', models.CharField(choices=[('upsert', 'upsert'), ('delete', 'delete')], max_length=8)),
                ('changed_fields', models.TextField(blank=True, null=True)),
                ('client_updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'sync_outbox',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['pushed_at', 'created_at'], name='sync_outbox_pushed__b405bd_idx'), models.Index(fields=['table_name', 'entity_id'], name='sync_outbox_table_n_58cea1_idx')],
            },
        ),
    ]
