# Generated by Django 5.1.2 on 2026-06-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0029_syncoutbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='codecategorieaffaire',
            name='categorie_globale',
            field=models.CharField(blank=True, choices=[('civil', 'رموز الملفات بالمحاكم المدنية'), ('penal', 'رموز الملفات الجنحية'), ('admin', 'رموز الملفات بالمحاكم الإدارية'), ('commercial', 'رموز الملفات بالمحاكم التجارية')], default='', help_text='Grande famille (civil/pénal/admin/commercial)', max_length=20, verbose_name='الفئة العامة'),
        ),
        migrations.AddField(
            model_name='codecategorieaffaire',
            name='code_type',
            field=models.CharField(blank=True, db_index=True, help_text='Code du groupe / chambre (ex: 1100, 1200, 1300)', max_length=10, null=True, verbose_name='رمز الغرفة'),
        ),
        migrations.AddField(
            model_name='codecategorieaffaire',
            name='sous_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('ابتدائي', 'ابتدائي'), ('استئنافي', 'استئنافي')], default='', help_text='ابتدائي / استئنافي — utilisé pour la cascade mahakim.ma', max_length=20, verbose_name='النوع الفرعي'),
        ),
        migrations.AddField(
            model_name='codecategorieaffaire',
            name='type_libelle',
            field=models.CharField(blank=True, help_text='Libellé de la chambre (ex: مؤسسة الرئيس وغرفة المشورة, المدني)', max_length=200, null=True, verbose_name='تسمية الغرفة'),
        ),
        migrations.AddIndex(
            model_name='codecategorieaffaire',
            index=models.Index(fields=['code_type'], name='code_catego_code_ty_f94999_idx'),
        ),
        migrations.AddIndex(
            model_name='codecategorieaffaire',
            index=models.Index(fields=['sous_type'], name='code_catego_sous_ty_71bdec_idx'),
        ),
        migrations.AddIndex(
            model_name='codecategorieaffaire',
            index=models.Index(fields=['categorie_globale'], name='code_catego_categor_c77b80_idx'),
        ),
    ]
