# Generated by Django 5.1.2 on 2026-06-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocat_app', '0030_codecategorieaffaire_hierarchie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codecategorieaffaire',
            name='sous_type',
            field=models.CharField(blank=True, default='', help_text='ابتدائي / استئنافي / محلي / إنابة / ... (texte libre depuis le XLSX)', max_length=80, verbose_name='النوع الفرعي'),
        ),
    ]
