"""PWA endpoints — manifest and service worker.

Both are served from the site root so the SW scope covers everything.
Static assets they reference (icons) live under static/pwa/.
"""
from django.http import HttpResponse, JsonResponse
from django.templatetags.static import static
from django.views.decorators.cache import cache_control
from django.views.decorators.http import require_GET


@require_GET
@cache_control(max_age=3600)
def manifest(request):
    """Web App Manifest — the document browsers read to decide installability."""
    data = {
        "name": "مكتب المحاماة",
        "short_name": "المكتب",
        "description": "تطبيق إدارة المحاماة",
        "lang": "ar",
        "dir": "rtl",
        "start_url": "/",
        "scope": "/",
        "display": "standalone",
        "orientation": "any",
        "background_color": "#f3ecdc",
        "theme_color": "#0e5f3f",
        "categories": ["productivity", "business"],
        "icons": [
            {
                "src": static("pwa/icon-192.png"),
                "sizes": "192x192",
                "type": "image/png",
                "purpose": "any",
            },
            {
                "src": static("pwa/icon-512.png"),
                "sizes": "512x512",
                "type": "image/png",
                "purpose": "any",
            },
            {
                "src": static("pwa/icon-192-maskable.png"),
                "sizes": "192x192",
                "type": "image/png",
                "purpose": "maskable",
            },
            {
                "src": static("pwa/icon-512-maskable.png"),
                "sizes": "512x512",
                "type": "image/png",
                "purpose": "maskable",
            },
        ],
    }
    response = JsonResponse(data)
    response["Content-Type"] = "application/manifest+json; charset=utf-8"
    return response


SW_BODY = r"""// service worker — generated by avocat_app.views_pwa.service_worker
// Strategy:
//   * Static assets (/static/, /media/)  : cache-first, lazy fill
//   * Navigation GETs                    : network-first, cache fallback
//   * Mutations (POST/PUT/DELETE/PATCH)  : passthrough (offline = error,
//     queue handled by Phase 5 background sync later)

const CACHE = "avocat-v__VERSION__";
const APP_SHELL = [
    "/",
    "/static/pwa/icon-192.png",
    "/static/pwa/icon-512.png",
];

self.addEventListener("install", (e) => {
    e.waitUntil(
        caches.open(CACHE).then((c) => c.addAll(APP_SHELL).catch(() => null))
    );
    self.skipWaiting();
});

self.addEventListener("activate", (e) => {
    e.waitUntil(
        caches.keys().then((keys) =>
            Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
        )
    );
    self.clients.claim();
});

function isAsset(url) {
    return url.pathname.startsWith("/static/") || url.pathname.startsWith("/media/");
}

async function cacheFirst(request) {
    const cached = await caches.match(request);
    if (cached) return cached;
    try {
        const res = await fetch(request);
        if (res.ok) {
            const cache = await caches.open(CACHE);
            cache.put(request, res.clone());
        }
        return res;
    } catch (err) {
        return cached || Response.error();
    }
}

async function networkFirst(request) {
    try {
        const res = await fetch(request);
        if (res.ok && request.method === "GET") {
            const cache = await caches.open(CACHE);
            cache.put(request, res.clone());
        }
        return res;
    } catch (err) {
        const cached = await caches.match(request);
        if (cached) return cached;
        return new Response(
            "<h1>غير متصل</h1><p>هذه الصفحة غير متوفّرة دون اتصال بعد.</p>",
            { status: 503, headers: { "Content-Type": "text/html; charset=utf-8" } }
        );
    }
}

self.addEventListener("fetch", (event) => {
    const { request } = event;
    if (request.method !== "GET") return;  // mutations: passthrough
    const url = new URL(request.url);
    if (url.origin !== self.location.origin) return;  // 3rd-party: passthrough
    if (isAsset(url)) {
        event.respondWith(cacheFirst(request));
    } else if (request.mode === "navigate" || request.headers.get("Accept")?.includes("text/html")) {
        event.respondWith(networkFirst(request));
    }
});
"""


@require_GET
def service_worker(request):
    """Serve the SW from / so its scope covers the whole site.

    Browsers refuse to register a SW whose path is deeper than where it
    controls, so we keep the file at root — see https://w3c.github.io/ServiceWorker/#path-restriction.
    """
    from django.conf import settings
    version = getattr(settings, "PWA_VERSION", "1")
    body = SW_BODY.replace("__VERSION__", str(version))
    response = HttpResponse(body, content_type="application/javascript; charset=utf-8")
    response["Service-Worker-Allowed"] = "/"
    # SW file itself should never be cached aggressively — clients need to
    # detect updates so they can re-install the new version.
    response["Cache-Control"] = "no-cache"
    return response
